name: SDK Screenshots

on:
  push:
  workflow_dispatch:

jobs:

  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          target: google_apis
          profile: Pixel 4 XL
          script: |
            avdmanager list
            adb logcat -c
            adb logcat *:E &
            ./gradlew clean

#      - name: Upload Screenshots Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: sdk-screenshots
#
#          path: screenshot/sdk/
#          retention-days: 5

